service: music-lab-api

frameworkVersion: '3'

plugins:
    - serverless-esbuild
    - serverless-offline
    - serverless-dotenv-plugin
    - serverless-domain-manager

custom:
    defaultStage: local
    stage: ${opt:stage, self:custom.defaultStage}
    dotenv:
        path: .env/.env.${self:custom.stage}
    domainEnabled:
        local: false
        dev: true
        prod: true
    apiDomains:
        local: ''
        dev: dev.api.music-lab.app
        prod: api.music-lab.app
    customDomain:
        domainName: ${self:custom.apiDomains.${self:custom.stage}}
        basePath: ''
        stage: ${self:custom.stage}
        certificateName: api.music-lab.app
        createRoute53Record: true
        enabled: ${self:custom.domainEnabled.${self:custom.stage}}
        endpointType: regional
        apiType: http
    esbuild:
        minify: true
        bundle: true
        watch:
            pattern: ['src/**/*.ts']
    serverless-offline:
        host: '0.0.0.0'

provider:
    name: aws
    runtime: nodejs18.x
    memorySize: 1024
    timeout: 20
    stage: ${self:custom.stage}
    profile: serverless-admin
    region: ap-southeast-1

functions:
    public-endpoint:
        handler: ./src/handlers/public.publicEndpointHandler
        events:
            - httpApi:
                  path: /{proxy+}
                  method: ANY
    private-endpoint:
        handler: ./src/handlers/private.privateEndpointHandler
        events:
            - httpApi:
                  path: /api/{proxy+}
                  method: ANY

package:
    individually: true
    patterns:
        - '!cert/**'
        - cert/${self:custom.stage}/**
